pipeline {
    agent any

    environment {
        PATH = "/usr/local/bin:$PATH"
        DOCKER_CREDENTIALS_ID = 'docker-credentials'
        DOCKER_IMAGE = "zeduarte/jenkins-image"
        DOCKER_REGISTRY = "https://index.docker.io/v1/"
        REPO_URL = 'https://github.com/JoseGDuarte/devops-24-25-1241914.git'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out from repository...'
                git branch: 'main', url: env.REPO_URL
            }
        }

        stage('Assemble') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    echo 'Assembling...'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean assemble'
                    sh 'mv build/libs/*.jar build/libs/app.jar'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    echo 'Testing...'
                    sh './gradlew test'
                    junit '**/build/test-results/test/*.xml'
                }
            }
        }
        stage('Javadoc') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    echo 'Generating Javadoc...'
                    sh './gradlew javadoc'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'build/docs/javadoc', reportFiles: 'index.html', reportName: 'Javadoc'])
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    echo 'Archiving...'
                    archiveArtifacts artifacts: 'build/libs/*.jar', allowEmptyArchive: true
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('CA1/Part3/react-and-spring-data-rest-basic') {
                    script {
                        echo 'Building Docker Image...'
                        sh 'docker info'
                        def image = docker.build("${DOCKER_IMAGE}:${BUILD_ID}", '.')
                        docker.withRegistry(DOCKER_REGISTRY, DOCKER_CREDENTIALS_ID) {
                            image.push()
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}